web/account/urls.py
from django.contrib.auth import views
from django.urls import path

from .views import Profile, trade, tradeHistory, wallet

app_name = "account"
urlpatterns = [
    path("wallet/", wallet, name="wallet"),
    path("wallet/<int:page>", wallet, name="wallet"),
    path("tradeHistory/", tradeHistory, name="tradeHistory"),
    path("tradeHistory/", tradeHistory, name="tradeHistory"),
    path("profile/", Profile.as_view(), name="profile"),
    path("trade/<str:pair>", trade, name="trade"),
    path("trade/", trade, name="trade"),
]

web/apps/account/urls.py
from django.urls import path

from .views import Profile, open_orders, trade_history, wallet

app_name = "account"
urlpatterns = [
    path("wallet/", wallet, name="wallet"),
    path("wallet/<int:page>", wallet, name="wallet"),
    path("trade-history/", trade_history, name="tradeHistory"),
    path("trade-history/", trade_history, name="tradeHistory"),
    path("open-orders/", open_orders, name="openOrders"),
    path("profile/", Profile.as_view(), name="profile"),
]

web/apps/exchange/urls.py
from django.urls import path

from .views import exchange_trade, markets, search_cryptos

app_name = "exchange"
urlpatterns = [
    path("markets/", markets, name="markets"),
    path("search/<str:value>", search_cryptos, name="search"),
    path("trade/<str:pair>", exchange_trade, name="exchange_trade"),
    path("trade/", exchange_trade, name="exchange_trade"),
]

web/config/urls.py
from account.views import Login, PasswordChange, PasswordReset, Register, activate
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import home

app_name = "config"
urlpatterns = [
    path("", home, name="home"),
    path("account/login/", Login.as_view(), name="login"),
    path("account/signup/", Register.as_view(), name="signUp"),
    path("account/password_reset/", PasswordReset.as_view(), name="password_reset"),
    path("account/password_change/", PasswordChange.as_view(), name="password_change"),
    path("account/activate/<uidb64>/<token>/", activate, name="activate"),
    path(settings.ADMIN_URL, admin.site.urls),
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("", include("exchange.urls")),
    path("account/", include("account.urls")),
    path("account/", include("django.contrib.auth.urls")),
    path("", include("social_django.urls", namespace="social")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "config.views.page_not_found_view"
handler500 = "config.views.handler500"
handler403 = "config.views.handler403"

web/exchange/urls.py
from django.urls import path

from .views import (
    echo,
    home,
    markets,
    portfolio,
    recentTrades,
    search,
    trade,
    tradinghistory,
)

app_name = "exchange"
urlpatterns = [
    path("", home, name="home"),
    path("markets/", markets, name="markets"),
    path("trade/<str:value>", trade, name="trade"),
    path("portfolio/", portfolio, name="portfolio"),
    path("tradinghistory/", tradinghistory, name="tradinghistory"),
    path("recentTrades/", recentTrades, name="recentTrades"),
    path("echo/", echo, name="echo"),
    path("search/<str:value>", search, name="search"),
]

web/apps/exchange/models.py
import requests
from django.conf import settings
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db import models


class Portfolio(models.Model):
    MARKET_TYPES = (
        ("spot", "spot"),
        ("futures", "futures")
    )
    usr = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    cryptoName = models.CharField(max_length=255)
    amount = models.FloatField(default=0, null=True)
    equivalentAmount = models.FloatField(default=0, null=True, blank=True)
    marketType = models.CharField(max_length=10, default="spot", choices=MARKET_TYPES)

    def __str__(self):
        return f"{self.usr} {self.cryptoName}"

    @property
    def get_dollar_equivalent(self):
        response = requests.get(
            f"https://min-api.cryptocompare.com/data/price?fsym={self.cryptoName}&tsyms=USDT"
        ).json()
        price = float(response['USDT'])

        return price * self.amount


# details of terminated spot orders
class TradeHistory(models.Model):
    TRADE_TYPES = (
        ("buy", "buy"),
        ("sell", "sell")
    )
    ORDER_TYPES = (
        ("market", "market"),
        ("limit", "limit")
    )
    usr = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    type = models.CharField(max_length=4, choices=TRADE_TYPES)
    pair = models.CharField(max_length=255)
    pairPrice = models.FloatField()
    orderType = models.CharField(max_length=15, choices=ORDER_TYPES)
    histAmount = models.JSONField(default=None, blank=True, null=True)
    amount = models.CharField(max_length=255)
    time = models.DateTimeField(auto_now=True)
    complete = models.BooleanField(default=True)

    def humanizeTime(self):
        return naturaltime(self.time)

    humanizeTime.short_description = "Time"

    def __str__(self):
        return f"{self.usr} {self.pair}"

    class Meta:
        verbose_name_plural = "Trade histories"

web/apps/exchange/views.py
import json
import urllib.parse

import requests
from core.utils import search_symbol
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from requests.structures import CaseInsensitiveDict


def exchange_trade(request, pair=None):

    if not pair:
        return redirect(reverse("exchange:exchange_trade", kwargs={"pair": "BTC-USDT"}))

    name = pair.split("-")[0]
    pair = search_symbol(pair)
    context = {"pair": pair, "name": name.upper()}

    if not pair:
        pair = "BINANCE:BTCUSDT"
        name = "BTC"

        context = {
            "pair": pair,
            "name": name.upper(),
        }
        return redirect(reverse("exchange:exchange_trade", kwargs={"pair": "BTC-USDT"}))
    else:
        return render(request, "registration/trade.html", context=context)


def search_cryptos(request, value):

    headers = CaseInsensitiveDict()
    url = "https://arzdigital.com/wp-admin/admin-ajax.php"
    headers["Content-Type"] = "application/x-www-form-urlencoded"

    encoddedValue = urllib.parse.quote_plus(json.dumps({"s": value}))
    data = f"action=arzAjax&query=search&data={encoddedValue}"

    try:
        resp = requests.post(url, headers=headers, data=data).json().get("coins", "null")
    except:
        resp = "null"

    if resp != "null":
        for item in resp:
            item["image"] = f'https://cdn.arzdigital.com/uploads/assets/coins/icons/32x32/{item["slug"]}.png'
    return JsonResponse(resp, safe=False)


def markets(request):
    return render(request, "exchange/markets.html")

web/exchange/views.py
import json
import re
import urllib.parse
import channels.layers
import requests
from account.models import User
from asgiref.sync import async_to_sync
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from requests.structures import CaseInsensitiveDict
from .common_functions import Give_equivalent
from .models import Portfolio, TradeHistory
from .trade import Trade


def home(request):
    return render(request, "exchange/index.html")


def search(request, value):

    headers = CaseInsensitiveDict()
    url = "https://arzdigital.com/wp-admin/admin-ajax.php"
    headers["Content-Type"] = "application/x-www-form-urlencoded"

    encoddedValue = urllib.parse.quote_plus(json.dumps({"s": value}))
    data = f"action=arzAjax&query=search&data={encoddedValue}"

    try:
        resp = requests.post(url, headers=headers, data=data).json().get("coins", "null")
    except:
        resp = "null"

    if resp != "null":
        for item in resp:
            item[
                "image"
            ] = f'https://cdn.arzdigital.com/uploads/assets/coins/icons/32x32/{item["slug"]}.png'
    return JsonResponse(resp, safe=False)


def signUp(request):
    return render(request, "registration/signup.html")


def markets(request):
    return render(request, "exchange/markets.html")


@login_required()
def trade(request, value):
    value = re.sub("'", '"', value)
    value = json.loads(value)

    tradeObject = Trade(request.user, "market", value["type"], value["pair"], value["amount"])
    result = tradeObject.result
    if result["state"] == 0:
        channel_layer = channels.layers.get_channel_layer()
        async_to_sync(channel_layer.group_send)(
            "orderBook", {"type": "order.display", "content": result}
        )
    return JsonResponse(result)


@login_required()
def portfolio(request):
    eq = Give_equivalent()
    resJson = dict()
    for index, item in enumerate(Portfolio.objects.filter(usr=request.user).iterator()):
        if item.cryptoName == "USDT":
            equivalentAmount = None
        else:
            equivalentAmount = eq.calc_equivalent(item.cryptoName, "USDT", item.amount)[1]
        resJson[index] = {
            "cryptoName": item.cryptoName,
            "amount": item.amount,
            "equivalentAmount": equivalentAmount,
            "marketType": item.marketType,
        }
    return JsonResponse(resJson)


@login_required()
def tradinghistory(request):
    resJson = dict()

    for index, item in enumerate(
        TradeHistory.objects.filter(usr=request.user, amount__gt=0).order_by("-time").iterator()
    ):
        resJson[index] = {
            "type": item.type,
            "pair": item.pair,
            "histAmount": item.histAmount,
            "amount": item.amount,
            "price": item.price,
            "time": item.time,
            "complete": item.complete,
            "orderType": item.orderType,
        }
    return JsonResponse(resJson)


def recentTrades(request):
    resJson = dict()
    for index, item in enumerate(
        TradeHistory.objects.filter(amount__gt=0).order_by("-time").iterator()
    ):
        resJson[index] = {
            "type": item.type,
            "pair": item.pair,
            "pairPrice": item.price,
            "amount": item.amount,
        }
    return JsonResponse(resJson)


def echo(request):
    return render(request, "exchange/echo.html")

web/apps/templates/exchange/base.html
{% load static %}
{% load gravatar %}

<!DOCTYPE html>
<html lang="en">

<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Exchange | {% block title %}{% endblock %}</title>
	<link rel="icon" href="{% static 'exchange/img/favicon.png' %}" type="image/x-icon">
	<link rel="stylesheet" href="{% static 'exchange/css/style.css' %}">
	<script src="{% static 'exchange/js/base/jquery-3.4.1.min.js' %}"></script>
	<meta name="google-site-verification" content="rlYNJsJJktY04G_LnK3oTwCloqeEWF3tcwk2cU2rWzk" />
	<!-- Google tag (gtag.js) -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-M8QWQYGT2M"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'G-M8QWQYGT2M');
	</script>
</head>

<body id="dark">
	<header class="dark-bb">
		<nav class="navbar navbar-expand-lg">
			<a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'exchange/img/logo-light.svg' %}" alt="logo"></a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#headerMenu"
				aria-controls="headerMenu" aria-expanded="false" aria-label="Toggle navigation">
				<i class="icon ion-md-menu"></i>
			</button>

			<div class="collapse navbar-collapse" id="headerMenu">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item dropdown">
						<a class="nav-link" href="{% url 'exchange:exchange_trade' %}" aria-haspopup="true"
							aria-expanded="false">
							Trade
						</a>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link" href="{% url 'exchange:markets' %}" aria-haspopup="true"
							aria-expanded="false">
							Markets
						</a>
					</li>

					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
							aria-expanded="false">
							Dashboard
						</a>
						<div class="dropdown-menu">
							<a class="dropdown-item" href="{% url 'account:profile' %}">Profile</a>
							<a class="dropdown-item" href="{% url 'account:wallet' %}">Wallet</a>
							<a class="dropdown-item" href="{% url 'account:tradeHistory' %}">Trade history</a>
							<a class="dropdown-item" href="{% url 'account:openOrders' %}">Open orders</a>
						</div>
					</li>
				</ul>
			
				{% if user.is_authenticated %}
				<li class="nav-item dropdown header-img-icon">
				<a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
							aria-expanded="false">
							<img src="{% gravatar_url user.email 150 %}" class="img-circle" alt="{{user.username}}'s avatar">
						</a>
						<div class="dropdown-menu">
							<div class="dropdown-header d-flex flex-column align-items-center">
								<div class="figure mb-3">
									<img src="{% gravatar_url user.email 150 %}" class="img-circle" alt="{{user.username}}'s avatar">
								</div>
								<div class="info text-center">
									<p class="name font-weight-bold mb-0">
										{% if user.get_full_name %}
												{{ user.get_full_name }}
										{% else %}
												{{ user.username }}
										{% endif %}
									</p>
									<p class="email text-muted mb-3">
										{{user.email}}
									</p>
								</div>
							</div>
							<div class="dropdown-body">
								<ul class="profile-nav">
									<li class="nav-item">
										<a href="{% url 'account:profile' %}" class="nav-link">
											<i class="icon ion-md-person"></i>
											<span>Profile</span>
										</a>
									</li>
									<li class="nav-item">
										<a href="{% url 'account:wallet' %}" class="nav-link">
											<i class="icon ion-md-wallet"></i>
											<span>My Wallet</span>
										</a>
									</li>
									<li class="nav-item">
										<a href="{% url 'account:tradeHistory' %}" class="nav-link">
											<i class="icon ion-md-settings"></i>
											<span>Trade history</span>
										</a>
									</li>
									<li class="nav-item">
										<a href="{% url 'account:openOrders' %}" class="nav-link">
										  <i class="icon ion-md-settings"></i>
										  <span>Open orders</span>
										</a>
									</li>
									<li class="nav-item" id="changeThemeDark">
										<a href="#!" class="nav-link">
										  <i class="icon ion-md-moon"></i>
										  <span>Theme</span>
										</a>
								  	</li>
									<li class="nav-item">
										<a href="{% url 'logout' %}" class="nav-link red">
											<i class="icon ion-md-power"></i>
											<span>Log Out</span>
										</a>
									</li>
								</ul>
							</div>
						</div>
					</li>
				{% else %}
					<ul class="navbar-nav ml-auto">
						<a href="{% url 'login' %}" class="btn-1">Sign In</a>
						<a href="{% url 'signUp' %}" class="btn-2">Get Started</a>
					</ul>
				{% endif %}
			</div>
		</nav>
	</header>

	{% block main %}

	{% endblock %}

	<script src="{% static 'exchange/js/base/popper.min.js' %}"></script>
	<script src="{% static 'exchange/js/base/bootstrap.min.js' %}"></script>
	<script src="{% static 'exchange/js/base/custom.js' %}"></script>
	<script>
		if (localStorage.getItem('theme') == 'true'){
			$('#changeThemeDark').click()
			$('.live-search-list').toggle();
		}
	</script>
</body>

</html>

web/apps/templates/exchange/footer.html
{% load static %}
<footer class="landing-footer-two">
  <div class="container">
	<div class="row">
	  <div class="col-md-4">
		<img src="{% static 'exchange/img/logo-light.svg' %}" alt="">
		<p>Crypo is the most advanced UI kit for making the Blockchain platform. This kit comes with 4 different
		  exchange page, market, wallet and many more</p>
		<ul class="social-icon">
		  <li><a href="#"><i class="icon ion-logo-facebook"></i></a></li>
		  <li><a href="#"><i class="icon ion-logo-twitter"></i></a></li>
		  <li><a href="#"><i class="icon ion-logo-linkedin"></i></a></li>
		  <li><a href="#"><i class="icon ion-logo-pinterest"></i></a></li>
		  <li><a href="#"><i class="icon ion-logo-github"></i></a></li>
		</ul>
	  </div>
	  <div class="col-md-2">
		<h3>Company</h3>
		<ul>
		  <li><a href="#">About</a></li>
		  <li><a href="#">Careers</a></li>
		  <li><a href="#">Affiliates</a></li>
		  <li><a href="#">Investors</a></li>
		  <li><a href="#">Legal & privacy</a></li>
		  <li><a href="#">Cookie policy</a></li>
		</ul>
	  </div>
	  <div class="col-md-2">
		<h3>Individuals</h3>
		<ul>
		  <li><a href="#">Buy & sell</a></li>
		  <li><a href="#">Earn free crypto</a></li>
		  <li><a href="#">Wallet</a></li>
		  <li><a href="#">Card</a></li>
		  <li><a href="#">Payment methods</a></li>
		  <li><a href="#">Account access</a></li>
		</ul>
	  </div>
	  <div class="col-md-2">
		<h3>Support</h3>
		<ul>
		  <li><a href="#">Help center</a></li>
		  <li><a href="#">Contact us</a></li>
		  <li><a href="#">Create account</a></li>
		  <li><a href="#">ID verification</a></li>
		  <li><a href="#">Account information</a></li>
		  <li><a href="#">Supported crypto</a></li>
		</ul>
	  </div>
	  <div class="col-md-2">
		<h3>Learn</h3>
		<ul>
		  <li><a href="#">Browse crypto prices</a></li>
		  <li><a href="#">Crypto basics</a></li>
		  <li><a href="#">Tips & tutorials</a></li>
		  <li><a href="#">Market updates</a></li>
		  <li><a href="#">How to send crypto</a></li>
		  <li><a href="#">What is a blockchain?</a></li>
		</ul>
	  </div>
	</div>
  </div>
</footer>

web/apps/templates/exchange/index.html
{% extends 'exchange/base.html' %}

{% block title %}Home{% endblock %}

{% block main %}
{% load static %}

	<div class="landing-hero">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<h2>A trusted and secure cryptocurrency exchange.</h2>
					<p>Crypo is the most advanced UI kit for making the Blockchain platform.
						This kit comes with 4 different exchange page, market, wallet and many more</p>
				</div>
				<div class="offset-md-1 col-md-5">
					<img src="{% static 'exchange/img/landing.png' %}" alt="bitcoin">
				</div>
			</div>
		</div>
	</div>

	<div class="landing-feature landing-coin-price bt-none">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h2>Check your favorite coin price <br> within a glance</h2>
				</div>
				<div class="col-md-6">
					<!-- TradingView Widget BEGIN -->
					<div class="tradingview-widget-container">
						<div class="tradingview-widget-container__widget"></div>
						<script type="text/javascript"
							src="https://s3.tradingview.com/external-embedding/embed-widget-mini-symbol-overview.js" async>
								{
									"symbol": "BINANCE:BTCUSDT",
									"width": "100%",
									"height": 220,
									"locale": "en",
									"dateRange": "12M",
									"colorTheme": "dark",
									"trendLineColor": "rgba(41, 98, 255, 1)",
									"underLineColor": "rgba(41, 98, 255, 0.3)",
									"underLineBottomColor": "rgba(41, 98, 255, 0)",
									"isTransparent": true,
									"autosize": false,
									"largeChartUrl": ""
								}
							</script>
					</div>
					<!-- TradingView Widget END -->
				</div>
				<div class="col-md-6">
					<!-- TradingView Widget BEGIN -->
					<div class="tradingview-widget-container">
						<div class="tradingview-widget-container__widget"></div>
						<script type="text/javascript"
							src="https://s3.tradingview.com/external-embedding/embed-widget-mini-symbol-overview.js" async>
								{
									"symbol": "BINANCE:ETHUSDT",
									"width": "100%",
									"height": 220,
									"locale": "en",
									"dateRange": "12M",
									"colorTheme": "dark",
									"trendLineColor": "rgba(41, 98, 255, 1)",
									"underLineColor": "rgba(41, 98, 255, 0.3)",
									"underLineBottomColor": "rgba(41, 98, 255, 0)",
									"isTransparent": true,
									"autosize": false,
									"largeChartUrl": ""
								}
							</script>
					</div>
					<!-- TradingView Widget END -->
				</div>
				</div>
			</div>
		</div>
	</div>
	<div class="landing-feature">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h2>Check latest news and key events of popular <br> companies and cryptocurrencies</h2>
				</div>
				<div class="col-md-12">
					<!-- TradingView Widget BEGIN -->
					<div class="tradingview-widget-container">
						<div class="tradingview-widget-container__widget"></div>
						<script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-timeline.js"
							async>
								{
									"colorTheme": "dark",
									"isTransparent": true,
									"displayMode": "compact",
									"width": "100%",
									"height": 430,
									"locale": "en"
								}
							</script>
					</div>
					<!-- TradingView Widget END -->
				</div>
			</div>
		</div>
	</div>

{% include 'exchange/footer.html' %}
{% endblock %}

web/apps/templates/exchange/markets.html
{% extends 'exchange/base.html' %}

{% block title %}Markets Info{% endblock %}

{% block main %}
{% load static %}

 <div class="markets ptb70">
	<div class="container">
	  <div class="row">
		<div class="d-none d-lg-flex">
		  <div class="col-md-4">
		  <!-- TradingView Widget BEGIN -->
		  <div class="tradingview-widget-container">
			<div class="tradingview-widget-container__widget"></div>
			<script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-mini-symbol-overview.js" async>
			{
			"symbol": "CRYPTOCAP:BTC.D",
			"width": "350",
			"height": "250",
			"locale": "en",
			"dateRange": "12M",
			"colorTheme": "light",
			"trendLineColor": "rgba(41, 98, 255, 1)",
			"underLineColor": "rgba(41, 98, 255, 0.3)",
			"underLineBottomColor": "rgba(41, 98, 255, 0)",
			"isTransparent": true,
			"autosize": false,
			"largeChartUrl": ""
		  }
			</script>
		  </div>
		  <!-- TradingView Widget END -->
			<br>
		  </div>
		  <div class="col-md-4">
			<!-- TradingView Widget BEGIN -->
			<div class="tradingview-widget-container">
			  <div class="tradingview-widget-container__widget"></div>
			  <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-mini-symbol-overview.js" async>
			  {
			  "symbol": "CRYPTOCAP:TOTAL",
			  "width": "350",
			  "height": "250",
			  "locale": "en",
			  "dateRange": "12M",
			  "colorTheme": "light",
			  "trendLineColor": "rgba(41, 98, 255, 1)",
			  "underLineColor": "rgba(41, 98, 255, 0.3)",
			  "underLineBottomColor": "rgba(41, 98, 255, 0)",
			  "isTransparent": true,
			  "autosize": false,
			  "largeChartUrl": ""
			}
			  </script>
			</div>
			<!-- TradingView Widget END -->
		  </div>
		  <div class="col-md-4">
		  <!-- TradingView Widget BEGIN -->
		  <div class="tradingview-widget-container">
			<div class="tradingview-widget-container__widget"></div>
			<script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-mini-symbol-overview.js" async>
			{
			"symbol": "CRYPTOCAP:OTHERS.D",
			"width": "350",
			"height": "250",
			"locale": "en",
			"dateRange": "12M",
			"colorTheme": "light",
			"trendLineColor": "rgba(41, 98, 255, 1)",
			"underLineColor": "rgba(41, 98, 255, 0.3)",
			"underLineBottomColor": "rgba(41, 98, 255, 0)",
			"isTransparent": true,
			"autosize": false,
			"largeChartUrl": ""
		  }
			</script>
		  </div>
		  <!-- TradingView Widget END -->
		  </div>
		</div>
		<div class="col-md-12">
		  <div class="markets-pair-list">

			<div class="input-group">
	
			  <input id="inputBox" type="text" class="live-search-box" placeholder="search here" />
			  
			  <ul class="live-search-list" style="display: none !important" id='searchParent'>
				
				<li id='res' class="d-none">
				  <p style="color: black;">Nothing found!</p>
				</li>

				<li id='loading' class="d-none">
				  <p style="color: black;">Loading...</p>
				</li>
				<div id="searchBefore"></div>

			  </ul>

			</div>

			<div class="tab-content">
			  <div class="tab-pane fade show" style="display:block; overflow-x: scroll;">
				<table class="table">
				  <thead>
					<tr style="cursor:auto">
					  <th>Rank</th>
					  <th>Coin</th>
					  <th>Last Price</th>
					  <th>Change (24H)</th>
					  <th>High (24H)</th>
					  <th>Low (24H)</th>
					  <th>Volume (24h)</th>
					  <th>Marketcap</th>
					</tr>
				  </thead>
				  <tbody id='cryptos'>
				  <div id='before'></div>
				  </tbody>
				</table>
			  </div>
			</div>
		</div>
	</div>
</div>
</div>
<div class="container paginator-container">
	<div class="row">
		<div class="col-5">
			<button id="paginationPrev" href="#" class="prev-next btn">Previous</button>
		</div>
		<div class="col-2">
			<span id="paginationText" class="green pagination-number"></span>
		</div>
		<div class="col-5">
			<button id="paginationNext" href="#" class="prev-next btn">Next</button>
		</div>
	</div>
</div>
</div>

<script src="{% static 'exchange/js/markets.js' %}"></script>
<script src="{% static 'exchange/js/search.js' %}"></script>
{% endblock %}